### ISSUE TITLE
yFi doesn't work on Apple Silicon

### ISSUE THREAD

**Issue by LOVEFIR3** [rose-m/yFi-app#3]
The idea seems great. Sadly it doesn't work on my Mac. I am using macOS 13.5 on a M2 MacBook Air 15". The apple is written in Intel 64 Base Architecture and need to be native to Apple Silicon. Suggest either Separate apps for each Intel and ARM or a Universal app. (I also left a response on produthunt since im unsure of you main channel for communication)

additionally your website also doesn't work. but with an app this small gidhub is sufficient to be honest.

**Comment by rose-m** [comment]
Thanks for actually heading out to the repo here! Yeah I haven't updated it in ages, sorry for that. I'll check and see if I can get a universal build done on the weekend, shouldn't be hard.
Website is down since I haven't fully moved hosters yet... 🙈

**Comment by LOVEFIR3** [comment]
Ah okay, no worries. I was also surprised there wasn’t more comments and reports considering a lot of ppl left reviews for liking the app. Im glad I was able to get in touch with you, no rush take your time, but I do appreciate you getting back to me. 

Best,
Stefan

**Comment by rose-m** [comment]
Finally got around to do it - and the new version should already be published! Let me know if it now works for you! (Also the website should be back up: https://yfi.coderose.io)

**Comment by LOVEFIR3** [comment]
thanks for the update, it works now!

so i have been using it the past day or so and my TX rate bounces back and
forth from 229 to 1080, and sometimes 229 to 1200. which got me thinking
this is due to a few things. one mainly being wifi interference which cant
be solved by just reconnecting every 2 seconds to keep a stable
conference call whihc is more just a bandaid fix, but still useful. This
issue mostly lies in users have the samel wifi channel as others around
them and there is crosstalk and interference bc of it. unless the wifi is
on a unused or low use channel there is as you know going to be some degree
of interference. another issue is the router it self and how it manages the
TX and RX rates which is generally out of anyones control especially if
your dealing with a ISP brand device like most users. i just wanted to
shoot some thoughts about this since while i think it best to educate users
no how to get the best conncetion its also very messy and complex for most
tech illeriate users.

**Comment by rose-m** [comment]
Yeah good point - I actually also set the rate limit very low (like < 100) as usually this indicates a "real" problem. Agree the pure rate is very bouncy. It might be a good idea to add a FAQ section or tips section to the website and link users from the popover where they can do configuration. The channel issue is extremely annoying, I've had that at home, too.
And yes, this tiny tool was meant as a bandaid fix since in my previous flat there were no not-crowded channels (even 5Ghz band didn't solve it) 🙈
